### ISSUE TITLE
a null

### ISSUE THREAD

**Issue by MindShow** [SpinalHDL/SpinalHDL#1116]
# test code
```scala
case class MyIOA(xEn:Boolean = false) extends BlackBox {
  val io = new Bundle{
    val x = in(Bool()).genIf(xEn)
    val y = in(Bool())
  }
  addPrePopTask(() => {
    io.flattenForeach(port => {
      println(port.name)
    })
  })
}

case class MyIOB(xEn: Boolean = false) extends Component {
  val io = new Bundle {
    val x = in(Bool()).genIf(xEn)
    val y = in(Bool())
  }

}

case class MyIOTest(xEn:Boolean = false) extends Component {
  val io = new Bundle{
    val aIo = new Bundle {
      val x = in(Bool()).genIf(xEn)
      val y = in(Bool())
    }
    val bIo = new Bundle {
      val x = in(Bool()).genIf(xEn)
      val y = in(Bool())
    }
  }
  val myIoA= MyIOA()
  val myIoB= MyIOB()
  io.aIo <> myIoA.io
  io.bIo <> myIoB.io
}

object MyMain{
  def main(args: Array[String]){
    SpinalConfig().generateVerilog(MyIOTest())
  }
}
```

# Error

```
 Error detected in phase PhaseCheck_noLatchNoOverride
********************************************************************************
********************************************************************************

NO DRIVER ON (toplevel/myIoA/??? : in Bool), defined at
    al.MyIOA$$anon$15.<init>(al.scala:791)
    al.MyIOA.<init>(al.scala:790)
    al.MyIOTest.<init>(al.scala:820)
    al.MyMain$$anonfun$main$1.apply(al.scala:828)
    al.MyMain$$anonfun$main$1.apply(al.scala:828)
    spinal.sim.JvmThread.run(SimManager.scala:51)


********************************************************************************
********************************************************************************

Design's errors are listed above.
SpinalHDL compiler exit stack : 

	at spinal.core.SpinalExit$.apply(Misc.scala:440)
	at spinal.core.SpinalError$.apply(Misc.scala:495)
	at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:175)
	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:191)
	at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$139.apply(Phase.scala:2894)
	at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$139.apply(Phase.scala:2892)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2892)
	at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2828)
	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2828)
	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2823)
	at spinal.core.Spinal$.apply(Spinal.scala:412)
	at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:178)
	at al.MyMain$.main(al.scala:828)
	at al.MyMain.main(al.scala)

进程已结束,退出代码1

```

**Comment by MindShow** [comment]
# this can work
```scala
case class MyIOA(xEn:Boolean = false) extends BlackBox {
  val io = new Bundle{
    val x = if(xEn) in(Bool()) else new BoolPoison
    val y = in(Bool())
  }
  addPrePopTask(() => {
    io.flattenForeach(port => {
      println(port.name)
    })
  })
}

case class MyIOB(xEn: Boolean = false) extends Component {
  val io = new Bundle {
      val x = in(Bool()).genIf(xEn)
    val y = in(Bool())
  }

}

case class MyIOTest(xEn:Boolean = false) extends Component {
  val io = new Bundle{
    val aIo = new Bundle {
      val x = if(xEn) in(Bool()) else new BoolPoison
      val y = in(Bool())
    }
    val bIo = new Bundle {
      val x = in(Bool()).genIf(xEn)
      val y = in(Bool())
    }
  }
  val myIoA= MyIOA()
  val myIoB= MyIOB()
  io.aIo <> myIoA.io
  io.bIo <> myIoB.io
}

object MyMain{
  def main(args: Array[String]){
    SpinalConfig().generateVerilog(MyIOTest())
  }
}
```

**Comment by MindShow** [comment]
# or this
```
case class MyIOA(xEn:Boolean = false) extends BlackBox {
  val io = new Bundle{
    val x = xEn generate in(Bool())
    val y = in(Bool())
  }
  addPrePopTask(() => {
    io.flattenForeach(port => {
      println(port.name)
    })
  })
}

case class MyIOB(xEn: Boolean = false) extends Component {
  val io = new Bundle {
      val x = xEn generate in(Bool())
    val y = in(Bool())
  }

}

case class MyIOTest(xEn:Boolean = false) extends Component {
  val io = new Bundle{
    val aIo = new Bundle {
      val x = if(xEn) in(Bool()) else new BoolPoison
      val y = in(Bool())
    }
    val bIo = new Bundle {
      val x = in(Bool()).genIf(xEn)
      val y = in(Bool())
    }
  }
  val myIoA= MyIOA()
  val myIoB= MyIOB()
  io.aIo <> myIoA.io
  io.bIo <> myIoB.io
}

object MyMain{
  def main(args: Array[String]){
    SpinalConfig().generateVerilog(MyIOTest())
  }
}
```

**Comment by Readon** [comment]
I have checked code about genIf function, it seems that it is a deprecated one. How about give out a warning while it is used?
The latest usage of genIf is [here](https://github.com/SpinalHDL/SpinalHDL/blob/4a56ace222042cd4ca1e8dd1f8ab459b598859b0/lib/src/main/scala/spinal/lib/blackbox/lattice/ice40/Blackbox.scala#L341) which might be affected if deprecated warning is added.
@andreasWallner do you have any concern about this?

**Comment by andreasWallner** [comment]
@Readon I checked, both the option most used in the codebase
```scala
case class TestBundle(s: Boolean) extends Bundle {
  val x = Bool()
  val y = if(s) Bool() else null
}
``` 
and the one that I have been playing around with lately
```scala
case class TestBundle(s: Boolean) extends Bundle {
  val x = Bool()
  val y = if(s) Some(Bool()) else None
}
```
don't have the same problem, didn't know about that when I used `genIf` for the Blackbox.
I'll open a PR that changes the use in the PLL and adds a deprecation notice to `genIf`

@MindShow Thanks for bringing this up, just as a note: there should not be a need to use `BoolPoison` - the version with `null` should work.

**Comment by Readon** [comment]
> 

There is a ```generate``` function of Boolean type could do the same thing and is widely adopted.

**Comment by Readon** [comment]
It might be more useful to have it described in the documents.
