### ISSUE TITLE
“object SdramXdrDdr2SpinalSim extends App” Error detected in phase PhaseNormalizeNodeInputs

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalHDL#1133]
The path of this file is “tester/src/test/scala/spinal/tester/scalatest/SdramXdrSdrSpinalSim.scala”，When running object SdramXdrDdr2SpinalSim, the following error is reported.

[Runtime] SpinalHDL dev    git head : af55caaf3e9821eed2b2ad2d5bfda742716bcb43
[Runtime] JVM max memory : 30688.0MiB
[Runtime] Current date : 2023.06.06 10:31:13
[Progress] at 0.000 : Elaborate components
[Progress] at 0.411 : Checks and transforms

**********************************************************************************************
[Warning] Elaboration failed (3 errors).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 0.595 : Elaborate components
[Progress] at 0.704 : Checks and transforms
Exception in thread "main" spinal.core.SpinalExit: 

 Error detected in phase PhaseNormalizeNodeInputs
********************************************************************************
********************************************************************************

WIDTH MISMATCH (13 bits <- 37 bits) on (toplevel/ctrl/core/tasker/inputsArbiter_selPayload_context :  Bits[13 bits]) := mux of Bits[37 bits] at 
    spinal.lib.MuxOHImpl.apply(Utils.scala:102)
    spinal.lib.MuxOHImpl.apply(Utils.scala:95)
    spinal.lib.MuxOHImpl.apply(Utils.scala:94)
    spinal.lib.memory.sdram.xdr.Tasker$$anon$6.<init>(Tasker.scala:164)
    spinal.lib.memory.sdram.xdr.Tasker.<init>(Tasker.scala:144)
    spinal.lib.memory.sdram.xdr.Core.<init>(Core.scala:31)
    spinal.lib.memory.sdram.xdr.CtrlWithoutPhy.<init>(CtrlWithPhy.scala:78)
    spinal.tester.scalatest.SdrXdrCtrlPlusPhy.<init>(SdramXdrSdrSpinalSim.scala:21)
    spinal.tester.scalatest.SdramXdrCtrlPlusRtlPhy.<init>(SdramXdrSdrSpinalSim.scala:29)
    spinal.tester.scalatest.SdramXdrTesterHelpers$$anonfun$complied$1.apply(SdramXdrSdrSpinalSim.scala:548)
    spinal.tester.scalatest.SdramXdrTesterHelpers$$anonfun$complied$1.apply(SdramXdrSdrSpinalSim.scala:534)
    spinal.sim.JvmThread.run(SimManager.scala:51)

********************************************************************************
********************************************************************************

WIDTH MISMATCH (37 bits <- 13 bits) on (toplevel/ctrl/core/tasker/inputsArbiter_output_payload_context :  Bits[37 bits]) := (toplevel/ctrl/core/tasker/inputsArbiter_selPayload_context :  Bits[13 bits]) at 
    spinal.lib.memory.sdram.xdr.Tasker$$anon$6.<init>(Tasker.scala:167)
    spinal.lib.memory.sdram.xdr.Tasker.<init>(Tasker.scala:144)
    spinal.lib.memory.sdram.xdr.Core.<init>(Core.scala:31)
    spinal.lib.memory.sdram.xdr.CtrlWithoutPhy.<init>(CtrlWithPhy.scala:78)
    spinal.tester.scalatest.SdrXdrCtrlPlusPhy.<init>(SdramXdrSdrSpinalSim.scala:21)
    spinal.tester.scalatest.SdramXdrCtrlPlusRtlPhy.<init>(SdramXdrSdrSpinalSim.scala:29)
    spinal.tester.scalatest.SdramXdrTesterHelpers$$anonfun$complied$1.apply(SdramXdrSdrSpinalSim.scala:548)
    spinal.tester.scalatest.SdramXdrTesterHelpers$$anonfun$complied$1.apply(SdramXdrSdrSpinalSim.scala:534)
    spinal.sim.JvmThread.run(SimManager.scala:51)

********************************************************************************
********************************************************************************

Design's errors are listed above.
SpinalHDL compiler exit stack : 

        at spinal.core.SpinalExit$.apply(Misc.scala:440)
        at spinal.core.SpinalError$.apply(Misc.scala:495)
        at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:177)
        at spinal.core.internals.PhaseContext.doPhase(Phase.scala:193)
        at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$140.apply(Phase.scala:2935)
        at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$140.apply(Phase.scala:2933)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2933)
        at spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2869)
        at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
        at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2869)
        at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2864)
        at spinal.core.Spinal$.apply(Spinal.scala:412)
        at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:178)
        at spinal.core.sim.SpinalSimConfig.compileCloned(SimBootstraps.scala:927)
        at spinal.core.sim.SpinalSimConfig.compile(SimBootstraps.scala:897)
        at spinal.tester.scalatest.SdramXdrTesterHelpers$.complied(SdramXdrSdrSpinalSim.scala:534)
        at spinal.tester.scalatest.SdramXdrDdr2SpinalSim$.delayedEndpoint$spinal$tester$scalatest$SdramXdrDdr2SpinalSim$1(SdramXdrSdrSpinalSim.scala:623)
        at spinal.tester.scalatest.SdramXdrDdr2SpinalSim$delayedInit$body.apply(SdramXdrSdrSpinalSim.scala:601)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at spinal.tester.scalatest.SdramXdrDdr2SpinalSim$.main(SdramXdrSdrSpinalSim.scala:601)
        at spinal.tester.scalatest.SdramXdrDdr2SpinalSim.main(SdramXdrSdrSpinalSim.scala)

**Comment by Dolu1990** [comment]
Should be all good now ^^
