### ISSUE TITLE
How to use clock generated by rtl in spinal sim?

### ISSUE THREAD

**Issue by developfpga** [SpinalHDL/SpinalHDL#1274]
I am trying to use clock generated by rtl in spinal sim, but it failed.
The clock of halfClockDomain is just 1/2 divider of default clock.
It failed at dut.halfClockDomain.waitSampling()

The error is 
[Progress] Verilator compilation started
[info] Found cached verilator binaries
[Progress] Verilator compilation done in 616.658 ms

[Progress] Start ClockDomainTest bringup simulation with seed 1779274381

[Error] Simulation failed at time=250

java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at spinal.core.sim.package$.spinal$core$sim$package$$btToSignal(package.scala:52)
	at spinal.core.sim.package$SimClockDomainPimper.getSignal(package.scala:609)
	at spinal.core.sim.package$SimClockDomainPimper.waitSampling(package.scala:646)
	at spinal.core.sim.package$SimClockDomainPimper.waitSampling(package.scala:642)
	at xxxxxxx.ClockDomainTester.$anonfun$new$4(ClockDomainTest.scala:45)
	at xxxxxxx.ClockDomainTester.$anonfun$new$4$adapted(ClockDomainTest.scala:42)
	at spinal.core.sim.SimCompiled.$anonfun$doSimApi$2(SimBootstraps.scala:608)
	at spinal.sim.SimManager.threadBody$1(SimManager.scala:229)
	at spinal.sim.SimManager.$anonfun$run$1(SimManager.scala:232)
	at spinal.sim.SimThread.$anonfun$jvmThread$1(SimThread.scala:93)
	at spinal.sim.JvmThread.run(SimManager.scala:51)

The code is
import org.scalatest.funsuite.AnyFunSuite
import spinal.core._
import spinal.lib._
import spinal.core.sim._

case class ClockDomainTest() extends Component {
	val io = new {
		val d = in Bool()
		val q = out Bool()
		val half = out Bool()
	}

	io.q := io.d

	val half = Reg(Bool()) init(False)

	half := ~half

	io.half := half

	val halfClockDomain = ClockDomain(half, ClockDomain.current.readResetWire)
}

class ClockDomainTester extends AnyFunSuite {
	object SelfSimConfig {
		def apply() = SimConfig.withWave.withConfig(SpinalConfig(targetDirectory = "gen", defaultConfigForClockDomains = ClockDomainConfig(resetKind = SYNC))).workspacePath("sim")
	}
	var compiled: SimCompiled[ClockDomainTest] = null

	test("compiled") {
		compiled = SelfSimConfig().compile {
			val dut = new ClockDomainTest()
			dut
		}
	}

	test("bringup") {
		compiled.doSim("bringup") { dut =>
			dut.clockDomain.forkStimulus(10)
			dut.clockDomain.waitSampling(10)
			dut.halfClockDomain.waitSampling()
			SimTimeout(10000)
		}
	}
}`

**Comment by Dolu1990** [comment]
Hi,

I pushed a fix. where you just have to do half.simPublic() in the component.
Without that fix you would need to define half as 
- val half = out(Reg(Bool()) init(False))

SpinalHDL should be able to read it in sim (as long as it is in the toplevel)
