### ISSUE TITLE
Error when create a new ClockDomain in simulation

### ISSUE THREAD

**Issue by zyn810039594** [SpinalHDL/SpinalHDL#1317]
Hello,
I want to monitor a Axi bus inside the module, and it drives by a clock that is different from the input clock.
```scala
val perpPort = dut.socInst.logicMainInst.coreInst.io.d_perp // An AXI4 Port. This signal is set by "simPublic"
val cpuCd = ClockDomain(dut.socInst.logicMainInst.smuInst.io.coreClkRst.clk) // This signal is set by "simPublic"
val perpMoni = infoMonitor(perpPort,cpuCd) // a extend of Axi4WriteOnlyMonitor
```
And it reports error:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "spinal.core.internals.BaseNode.algoIncrementale()" because "bt" is null
	at spinal.core.sim.package$.spinal$core$sim$package$$btToSignal(package.scala:54)
	at spinal.core.sim.package$SimClockDomainPimper.getSignal(package.scala:671)
	at spinal.core.sim.package$SimClockDomainPimper.onSamplings(package.scala:964)
	at spinal.lib.sim.StreamMonitor.<init>(Stream.scala:28)
	at spinal.lib.sim.StreamMonitor$.apply(Stream.scala:12)
	at spinal.lib.bus.amba4.axi.sim.Axi4WriteOnlyMonitor.<init>(Agent.scala:499)
	at spinal.lib.bus.amba4.axi.sim.Axi4WriteOnlyMonitor.<init>(Agent.scala:465)
	at parrotSim.TestCase_coremark.infoMonitor.<init>(infoMonitor.scala:8)
	at parrotSim.TestCase_coremark.coremarkTB$$anonfun$2.apply(coremarkTB.scala:21)
	at parrotSim.TestCase_coremark.coremarkTB$$anonfun$2.apply(coremarkTB.scala:16)
	at spinal.core.sim.SimCompiled$$anonfun$doSimApi$2.apply$mcV$sp(SimBootstraps.scala:611)
	at spinal.sim.SimManager.spinal$sim$SimManager$$threadBody$1(SimManager.scala:230)
	at spinal.sim.SimManager$$anonfun$2.apply$mcV$sp(SimManager.scala:233)
	at spinal.sim.SimThread$$anonfun$1.apply$mcV$sp(SimThread.scala:93)
	at spinal.sim.JvmThread.run(SimManager.scala:51)
```
Why it comes? how should I solve it? Thanks for your help!

**Comment by zyn810039594** [comment]
@Dolu1990 Is there anyway to solve it?

**Comment by zyn810039594** [comment]
The root problem is found, open a issue with a example

**Comment by zyn810039594** [comment]
The root problem is found, open a issue with a example
