### ISSUE TITLE
`Union` elements cannot be accessed inside SpinalSim properly

### ISSUE THREAD

**Issue by KireinaHoro** [SpinalHDL/SpinalHDL#1342]
```scala
import spinal.core._
import spinal.core.sim._
import spinal.lib._
import spinal.lib.sim._

case class MyUnion() extends Union {
  val a = newElement(UInt(64 bits))
  val b = newElement(Bits(64 bits))
}

object TestUnionSim extends App {
  val sim = SimConfig.withConfig(SpinalConfig()).withVerilator.allOptimisation

  val dut = sim.compile(new Component {
    val o = out(MyUnion())

    o.a := U(32, 64 bits)
  })
  dut.doSim("access-union-member") { dut =>
    println(s"Output port as int: ${dut.o.a.get.toBigInt}")
  }
}
```

This results in the following error with SpinalSim:

```
[Progress] Verilator compilation done in 3051.907 ms
[Progress] Start unamed access-union-member simulation with seed 172859342
[Error] Simulation failed at time=0
It seems like you used some SpinalHDL hardware elaboration API in the simulation. If you did, you shouldn't.
Exception in thread "main" java.lang.NullPointerException
        at spinal.core.signalCache$.apply(Misc.scala:169)
        at spinal.core.signalCache$.apply(Misc.scala:172)
        at spinal.core.UnionElement.get(Union.scala:12)
        at pionic.TestUnionSim$.$anonfun$new$1(TestUnionSim.scala:22)
        at pionic.TestUnionSim$.$anonfun$new$1$adapted(TestUnionSim.scala:21)
        at spinal.core.sim.SimCompiled.$anonfun$doSimApi$2(SimBootstraps.scala:610)
        at spinal.sim.SimManager.threadBody$1(SimManager.scala:230)
        at spinal.sim.SimManager.$anonfun$run$1(SimManager.scala:233)
        at spinal.sim.SimThread.$anonfun$jvmThread$1(SimThread.scala:93)
        at spinal.sim.JvmThread.run(SimManager.scala:51)
```

Also, it's a bit unexpected that I have to use `.get` on the `UnionElement`; seems like the implicit cast didn't work without it:

```
[error] /local/home/pengxu/work-local/enzian-pio-nic/hw/spinal/pionic/TestUnionSim.scala:22:45: value toBigInt is not a member of spinal.core.UnionElement[spinal.core.UInt]
[error]     println(s"Output port as int: ${dut.o.a.toBigInt}")
```

**Comment by Dolu1990** [comment]
Hi,

Ahh that one is much more tricky, we would need to add some API in the union class specificaly to access stuff in it durring simulation.

Something in the kind of : 

```scala
dut.o.simGet(_.a)
```


Or something like it. tricky tricky
```
