### ISSUE TITLE
Problems with `setCompositeName` in combination with `removePruned`

### ISSUE THREAD

**Issue by knapheide** [SpinalHDL/SpinalHDL#1503]
```scala
object Test extends App {
  SpinalConfig(
    targetDirectory = "rtl",
    removePruned = true
  ).generateVerilog(new Component {
    setDefinitionName("PruningTest")
    val a = out port True
    val b = True.setCompositeName(a, "b")
    out port True.setCompositeName(b, "c")
  })
}
```

I would expect the above example to be equivalent to:

```scala
object Test extends App {
  SpinalConfig(
    targetDirectory = "rtl",
    removePruned = true
  ).generateVerilog(new Component {
    setDefinitionName("PruningTest")
    val a = out port True
    out port True.setCompositeName(a, "b_c")
  })
}
```

Instead, i get this exception:

```
[Runtime] SpinalHDL dev    git head : acb2a748c7cc488aba092e56fdea1bb3fa1e0cfa
[Runtime] JVM max memory : 30208.0MiB
[Runtime] Current date : 2024.08.12 18:10:09
[Progress] at 0.000 : Elaborate components
[Progress] at 0.121 : Checks and transforms

ERROR !
A null pointer access has been detected in the JVM.
This could happen when in your SpinalHDL description, you access an signal which is only defined further.
For instance :
  val result = Bool()
  result := a ^ b  //a and b can't be accessed there because they are only defined one line below (Software rule of execution order)
  val a,b = Bool()
          
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "spinal.core.Component.parents(spinal.core.Component, scala.collection.immutable.List)" because "from" is null
	at spinal.core.NameableByComponent.getPath(Trait.scala:223)
	at spinal.core.NameableByComponent.getPath$(Trait.scala:222)
	at spinal.core.BaseType.getPath(BaseType.scala:55)
	at spinal.core.NameableByComponent.isNamed(Trait.scala:260)
	at spinal.core.NameableByComponent.isNamed$(Trait.scala:257)
	at spinal.core.BaseType.isNamed(BaseType.scala:55)
	at spinal.core.Nameable.getName(Trait.scala:391)
	at spinal.core.Nameable.getName$(Trait.scala:387)
	at spinal.core.BaseType.spinal$core$NameableByComponent$$super$getName(BaseType.scala:55)
	at spinal.core.NameableByComponent.getName(Trait.scala:252)
	at spinal.core.NameableByComponent.getName$(Trait.scala:237)
	at spinal.core.BaseType.getName(BaseType.scala:55)
	at spinal.core.Nameable.getName(Trait.scala:385)
	at spinal.core.Nameable.getName$(Trait.scala:385)
	at spinal.core.BaseType.spinal$core$NameableByComponent$$super$getName(BaseType.scala:55)
	at spinal.core.NameableByComponent.getName(Trait.scala:221)
	at spinal.core.NameableByComponent.getName$(Trait.scala:221)
	at spinal.core.BaseType.getName(BaseType.scala:55)
	at spinal.core.Component.$anonfun$allocateNames$2(Component.scala:305)
	at spinal.core.Component.$anonfun$allocateNames$2$adapted(Component.scala:303)
	at spinal.core.internals.ScopeStatement.$anonfun$walkStatements$1(Statement.scala:160)
	at spinal.core.internals.ScopeStatement.$anonfun$walkStatements$1$adapted(Statement.scala:159)
	at spinal.core.internals.ScopeStatement.foreachStatements(Statement.scala:154)
	at spinal.core.internals.ScopeStatement.walkStatements(Statement.scala:159)
	at spinal.core.Component.allocateNames(Component.scala:303)
	at spinal.core.internals.PhaseAllocateNames.$anonfun$impl$272(Phase.scala:2482)
	at spinal.core.internals.PhaseAllocateNames.$anonfun$impl$272$adapted(Phase.scala:2481)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at spinal.core.internals.PhaseAllocateNames.impl(Phase.scala:2481)
	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:184)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2970)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2968)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2968)
	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:71)
	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2900)
	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2869)
	at spinal.core.Spinal$.apply(Spinal.scala:421)
	at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:187)
	at spinal.lib.Test$.delayedEndpoint$spinal$lib$Test$1(Test.scala:9)
	at spinal.lib.Test$delayedInit$body.apply(Test.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at spinal.lib.Test$.main(Test.scala:5)
	at spinal.lib.Test.main(Test.scala)
1 targets failed
lib[2.12.18].runMain Subprocess failed
```

**Comment by Dolu1990** [comment]
should be good now ^^
