### ISSUE TITLE
Run test for InterfaceTesterCocotbBoot failed when only use 2.11 scala compilier.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#1507]
When I test the #1506 with command 
`mill crossTester[2.11.12].test.testOnly *InterfaceTesterCocotbBoot` 
it reports that elorbration by compiler in version 2.11.12 failed, but pass when versions are 2.12 and 2.13. 
It seems that the failing happens when PhaseInterface, and warns that Bool could not be transformed to BoxedUnit.

Here is the log.
``` log
[Runtime] SpinalHDL dev    git head : 2f27fed99b4e0b6867281fa8af7decdb44feb4bd
[Runtime] JVM max memory : 30688.0MiB
[Runtime] Current date : 2024.08.18 20:53:17
[Progress] at 637.748 : Elaborate components
[Progress] at 637.750 : Checks and transforms
spinal.core.Interface.callModPort(Interface.scala:123)
spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3$$anon$1.<init>(PhaseVerilog.scala:394)
spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3.apply(PhaseVerilog.scala:392)
spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3.apply(PhaseVerilog.scala:384)
scala.collection.immutable.List.foreach(List.scala:392)
spinal.core.internals.PhaseInterface.emitInterface(PhaseVerilog.scala:384)
spinal.core.internals.PhaseInterface$$anonfun$impl$10$$anonfun$spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1$1.apply(PhaseVerilog.scala:452)
spinal.core.internals.PhaseInterface$$anonfun$impl$10$$anonfun$spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1$1.apply(PhaseVerilog.scala:451)
scala.collection.immutable.List.foreach(List.scala:392)
spinal.core.internals.PhaseInterface$$anonfun$impl$10.spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1(PhaseVerilog.scala:451)
spinal.core.internals.PhaseInterface$$anonfun$impl$10.apply(PhaseVerilog.scala:464)
spinal.core.internals.PhaseInterface$$anonfun$impl$10.apply(PhaseVerilog.scala:448)
spinal.core.internals.PhaseContext$$anonfun$walkDeclarations$1$$anonfun$apply$24.apply(Phase.scala:144)
spinal.core.internals.PhaseContext$$anonfun$walkDeclarations$1$$anonfun$apply$24.apply(Phase.scala:144)
spinal.core.internals.ScopeStatement$$anonfun$walkDeclarations$1.apply(Statement.scala:181)
spinal.core.internals.ScopeStatement$$anonfun$walkDeclarations$1.apply(Statement.scala:180)
spinal.core.internals.ScopeStatement.foreachStatements(Statement.scala:154)
spinal.core.internals.ScopeStatement.walkDeclarations(Statement.scala:180)
spinal.core.internals.PhaseContext$$anonfun$walkDeclarations$1.apply(Phase.scala:144)
spinal.core.internals.PhaseContext$$anonfun$walkDeclarations$1.apply(Phase.scala:144)
spinal.core.internals.PhaseContext$$anonfun$walkComponents$1.apply(Phase.scala:156)
spinal.core.internals.PhaseContext$$anonfun$walkComponents$1.apply(Phase.scala:156)
spinal.core.internals.GraphUtils$.walkAllComponents(Misc.scala:268)
spinal.core.internals.PhaseContext.walkComponents(Phase.scala:156)
spinal.core.internals.PhaseContext.walkDeclarations(Phase.scala:144)
spinal.core.internals.PhaseInterface.impl(PhaseVerilog.scala:448)
spinal.core.internals.PhaseContext.doPhase(Phase.scala:184)
spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$146.apply(Phase.scala:2970)
spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2$$anonfun$apply$146.apply(Phase.scala:2968)
scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2968)
spinal.core.internals.SpinalVerilogBoot$$anonfun$singleShot$2.apply(Phase.scala:2900)
spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:71)
spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2900)
spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2869)
spinal.core.Spinal$.apply(Spinal.scala:422)
spinal.core.SpinalConfig.generateSystemVerilog(Spinal.scala:188)
spinal.core.InterfaceTesterCocotbBoot.<init>(InterfaceTester.scala:217)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
java.base/java.lang.Class.newInstance(Class.java:645)
org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:454)
mill.testrunner.TestRunnerUtils$.runTestFramework0(TestRunnerUtils.scala:142)
mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:38)
mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:569)
mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:42)

**********************************************************************************************
[Warning] Elaboration failed (1 error).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 637.752 : Elaborate components
[Progress] at 637.754 : Checks and transforms
[32mInterfaceTesterCocotbBoot:[0m
[31mspinal.core.InterfaceTesterCocotbBoot *** ABORTED ***[0m
[31m  java.lang.ClassCastException: class spinal.core.Bool cannot be cast to class scala.runtime.BoxedUnit (spinal.core.Bool and scala.runtime.BoxedUnit are in unnamed module of loader 'app')[0m
[31m  at spinal.core.Interface.callModPort(Interface.scala:123)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3$$anon$1.<init>(PhaseVerilog.scala:394)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3.apply(PhaseVerilog.scala:392)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$emitInterface$3.apply(PhaseVerilog.scala:384)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:392)[0m
[31m  at spinal.core.internals.PhaseInterface.emitInterface(PhaseVerilog.scala:384)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$impl$10$$anonfun$spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1$1.apply(PhaseVerilog.scala:452)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$impl$10$$anonfun$spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1$1.apply(PhaseVerilog.scala:451)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:392)[0m
[31m  at spinal.core.internals.PhaseInterface$$anonfun$impl$10.spinal$core$internals$PhaseInterface$$anonfun$$insertIFmap$1(PhaseVerilog.scala:451)[0m
[31m  ...[0m
```

**Comment by Readon** [comment]
@yportne13 Would you please take a look at it?
Or maybe we need to consider removing the support of 2.11 then.
