### ISSUE TITLE
run spinalhdl in scala shell (sbt console)

### ISSUE THREAD

**Issue by curliph** [SpinalHDL/SpinalHDL#326]
HI guys, I am newbie to spinalHDL.
Usually, When I try to learn a new language, I prefer to try things handy, just like test anything of python in its shell. 
I can run scala perfectly in this way by run "sbt console".
But failed when I run syntax of spinalhdl. 
$cd spinalTemplateSbt && sbt console
.......
scala> import spinal.core._
import spinal.core._
scala> val value = UInt(8 bits)
java.lang.NullPointerException
   at spinal.core.BaseType.<init>(BaseType.scala:54)
   at spinal.core.BitVector.<init>(BitVector.scala:36)
   at spinal.core.UInt.<init>(UInt.scala:51)
   at spinal.core.UIntFactory$class.UInt(UInt.scala:32)
   at spinal.core.package$.UInt(core.scala:32)
   at spinal.core.UIntFactory$class.UInt(UInt.scala:34)
   at spinal.core.package$.UInt(core.scala:32)
   ... 40 elided
scala>

**Comment by Dolu1990** [comment]
Hi,

Basicaly, hardware statements realy need to be nested into a SpinalVerilog{ } / SpinalVhdl { } and idealy in a component.

As far i can see, i think that doing all of that in a shell will not be practical, as you realy need to define a full body
