### ISSUE TITLE
Simple Enum Randomly Fails

### ISSUE THREAD

**Issue by BracketMaster** [SpinalHDL/SpinalHDL#419]
I've got a very simple state machine [here](https://github.com/BracketMaster/SpinalTemplateSbt/blob/main/src/main/scala/ToyEnum.scala)
that uses enums.

It can be tested with: ``sbt "testOnly toyenum.EnumSimTest"``

It sometimes fails with the following:

```bash
[info]   java.lang.IndexOutOfBoundsException: 6
[info]   at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
[info]   at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
[info]   at spinal.core.binarySequential$.getElement(Enum.scala:315)
[info]   at spinal.core.sim.package$SimEnumPimper.toEnum(package.scala:416)
[info]   at toyenum.EnumSim$$anonfun$main$2$$anonfun$apply$1.apply$mcVI$sp(ToyEnum.scala:47)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at toyenum.EnumSim$$anonfun$main$2.apply(ToyEnum.scala:46)
[info]   at toyenum.EnumSim$$anonfun$main$2.apply(ToyEnum.scala:43)
[info]   at spinal.core.sim.SimCompiled$$anonfun$doSimApi$2.apply$mcV$sp(SimBootstraps.scala:409)
[info]   at spinal.sim.SimManager.spinal$sim$SimManager$$threadBody$1(SimManager.scala:219)
[info]   ...
```

Sometimes it passes just fine - this behavior seems somewhat
random.

**Comment by BracketMaster** [comment]
Seems we have a [resolution](https://gitter.im/SpinalHDL/SpinalHDL?at=60a2b22c9f2c352db115ea33)
