### ISSUE TITLE
Better error messages when doing hardware synthesis within simulation

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#518]
I tried doing something like `dut.io.gpioA.writeEnable(0)` (I wanted to read some bit) within simulation code and ran into the following stack trace:

```
Exception in thread "main" java.lang.NullPointerException
	at spinal.core.BaseType.assignFromImpl(BaseType.scala:207)
	at spinal.core.Assignable$class.compositAssignFrom(Trait.scala:284)
	at spinal.core.BaseType.compositAssignFrom(BaseType.scala:52)
	at spinal.core.Data$class.assignFrom(Data.scala:361)
	at spinal.core.BaseType.assignFrom(BaseType.scala:52)
	at spinal.core.BaseType.wrapWithBool(BaseType.scala:277)
	at spinal.core.BitVector.newExtract(BitVector.scala:300)
	at spinal.core.Bits.apply(Bits.scala:210)
```

I understand why hardware synthesis methods don't work within a simulation. But it would be cool if the error message didn't look like an internal error. Something like "don't call this method within a simulation, use `toLong` etc. instead"

**Comment by piegamesde** [comment]
Works as intended.
